/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.web;

import org.metafacture.fix.web.AbstractFixWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class FixWebModule extends AbstractFixWebModule {
}
