/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix;

import org.metafacture.fix.AbstractFixRuntimeModule;
import org.metafacture.fix.interpreter.FixInterpreter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FixRuntimeModule extends AbstractFixRuntimeModule {
  public Class<FixInterpreter> bindFixInterpreter() {
    return FixInterpreter.class;
  }
}
