/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.validation;

import org.metafacture.fix.validation.AbstractFixValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FixValidator extends AbstractFixValidator {
}
