/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.metafacture.fix.FixRuntimeModule;
import org.metafacture.fix.FixStandaloneSetup;
import org.metafacture.fix.ide.FixIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class FixIdeSetup extends FixStandaloneSetup {
  @Override
  public Injector createInjector() {
    FixRuntimeModule _fixRuntimeModule = new FixRuntimeModule();
    FixIdeModule _fixIdeModule = new FixIdeModule();
    return Guice.createInjector(Modules2.mixin(_fixRuntimeModule, _fixIdeModule));
  }
}
