/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.ide;

import org.metafacture.fix.ide.AbstractFixIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FixIdeModule extends AbstractFixIdeModule {
}
