/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix;

import org.metafacture.fix.FixStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FixStandaloneSetup extends FixStandaloneSetupGenerated {
  public static void doSetup() {
    new FixStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
