/*
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FixStandaloneSetup extends FixStandaloneSetupGenerated {

	def static void doSetup() {
		new FixStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
