/*
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.metafacture.fix.FixRuntimeModule
import org.metafacture.fix.FixStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FixIdeSetup extends FixStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FixRuntimeModule, new FixIdeModule))
	}
	
}
