/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.scoping;

import org.metafacture.fix.scoping.AbstractFixScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FixScopeProvider extends AbstractFixScopeProvider {
}
