/**
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.metafacture.fix.FixRuntimeModule;
import org.metafacture.fix.FixStandaloneSetup;
import org.metafacture.fix.ide.FixIdeModule;
import org.metafacture.fix.web.FixWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class FixWebSetup extends FixStandaloneSetup {
  @Override
  public Injector createInjector() {
    FixRuntimeModule _fixRuntimeModule = new FixRuntimeModule();
    FixIdeModule _fixIdeModule = new FixIdeModule();
    FixWebModule _fixWebModule = new FixWebModule();
    return Guice.createInjector(Modules2.mixin(_fixRuntimeModule, _fixIdeModule, _fixWebModule));
  }
}
