/*
 * generated by Xtext 2.17.0
 */
package org.metafacture.fix.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class FixWebModule extends AbstractFixWebModule {
}
